pypro/aperitivos/urls.py
from django.urls import path

from pypro.aperitivos.views import video, indice

app_name = 'aperitivos'
urlpatterns = [
    path('<slug:slug>', video, name='video'),
    path('', indice, name='indice'),
]

pypro/base/urls.py
from django.urls import path

from pypro.base.views import home

app_name = 'base'
urlpatterns = [
    path('', home, name='home'),
]

pypro/modulos/urls.py
from django.urls import path

from pypro.modulos.views import detalhe, aula, indice

app_name = 'modulos'
urlpatterns = [
    path('<slug:slug>', detalhe, name='detalhe'),
    path('aulas/<slug:slug>', aula, name='aula'),
    path('', indice, name='indice')
]

pypro/turmas/urls.py
from django.urls import path
from pypro.turmas.views import indice

app_name = 'turmas'
urlpatterns = [
    path('', indice, name='indice'),
]

pypro/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('contas/', include('django.contrib.auth.urls')),
    path('', include('pypro.base.urls')),
    path('aperitivos/', include('pypro.aperitivos.urls')),
    path('modulos/', include('pypro.modulos.urls')),
    path('turmas/', include('pypro.turmas.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(
        path('__debug__/', include(debug_toolbar.urls))
    )

pypro/aperitivos/models.py
from django.db import models
from django.urls import reverse


class Video(models.Model):
    titulo = models.CharField(max_length=32)
    slug = models.SlugField(max_length=32)
    vimeo_id = models.CharField(max_length=32)
    criado_em = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('aperitivos:video', args=(self.slug,))

    def __str__(self):
        return f'Video: {self.titulo}'

pypro/base/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.core.mail import send_mail
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given email and password.
        """
        if not email:
            raise ValueError("The given username must be set")
        email = self.normalize_email(email)
        # Lookup the real model class from the global app registry so this
        # manager method can be used in migrations. This is fine because
        # managers are by definition working on the real model.
        # GlobalUserModel = apps.get_model(
        #     self.model._meta.app_label, self.model._meta.object_name
        # )
        # username = GlobalUserModel.normalize_username(username) VERIFICAR COM O RENZO
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """
    App base User class.

    Email and password are required. Other fields are optional.
    """

    first_name = models.CharField(_("first name"), max_length=150, blank=True)
    email = models.EmailField(_("email address"), unique=True)
    is_staff = models.BooleanField(
        _("staff status"),
        default=False,
        help_text=_("Designates whether the user can log into this admin site."),
    )
    is_active = models.BooleanField(
        _("active"),
        default=True,
        help_text=_(
            "Designates whether this user should be treated as active. "
            "Unselect this instead of deleting accounts."
        ),
    )
    date_joined = models.DateTimeField(_("date joined"), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = "email"
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _("user")
        verbose_name_plural = _("users")

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = "%s" % (self.first_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

pypro/modulos/models.py
from django.db import models
from django.urls import reverse
from ordered_model.models import OrderedModel


class Modulo(OrderedModel):
    titulo = models.CharField(max_length=64)
    publico = models.TextField()
    descricao = models.TextField()
    slug = models.SlugField(unique=True)

    class Meta(OrderedModel.Meta):
        pass

    def __str__(self):
        return self.titulo

    def get_absolute_url(self):
        return reverse('modulos:detalhe', kwargs={'slug': self.slug})


class Aula(OrderedModel):
    titulo = models.CharField(max_length=64)
    slug = models.SlugField(unique=True)
    modulo = models.ForeignKey('Modulo', on_delete=models.PROTECT)
    order_with_respect_to = 'modulo'
    vimeo_id = models.CharField(max_length=32)

    class Meta(OrderedModel.Meta):
        pass

    def __str__(self):
        return self.titulo

    def get_absolute_url(self):
        return reverse('modulos:aula', kwargs={'slug': self.slug})

pypro/turmas/models.py
from django.contrib.auth import get_user_model
from django.db import models


class Turma(models.Model):
    nome = models.CharField(max_length=64)
    slug = models.SlugField(max_length=64)
    inicio = models.DateField()
    fim = models.DateField()
    alunos = models.ManyToManyField(get_user_model(), through='Matricula')


class Matricula(models.Model):
    data = models.DateTimeField(auto_now_add=True)
    usuario = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    turma = models.ForeignKey(Turma, on_delete=models.CASCADE)

    class Meta:
        unique_together = [['usuario', 'turma']]
        ordering = ['turma', 'data']

pypro/aperitivos/views.py
from django.shortcuts import render, get_object_or_404
from pypro.aperitivos.models import Video


def video(request, slug):
    video = get_object_or_404(Video, slug=slug)
    return render(request, 'aperitivos/video.html', context={'video': video})


def indice(request):
    videos = Video.objects.order_by('criado_em').all()
    return render(request, 'aperitivos/indice.html', context={'videos': videos})

pypro/base/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'base/home.html')

pypro/modulos/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from pypro.modulos import facade


def detalhe(request, slug):
    modulo = facade.encontrar_modulo(slug)
    aulas = facade.lista_aulas_de_modulos_ordenadas(modulo)
    return render(request, 'modulos/modulo_detalhe.html', {'modulo': modulo, 'aulas': aulas})


@login_required
def aula(request, slug):
    aula = facade.encontrar_aula(slug)
    return render(request, 'modulos/aula_detalhe.html', {'aula': aula})


def indice(request):
    contexto = {'modulos': facade.listar_modulos_com_aulas()}
    return render(request, 'modulos/indice.html', contexto)

pypro/turmas/views.py
from django.shortcuts import render


def indice(request):
    return render(request, 'turmas/indice.html')

pypro/aperitivos/templates/aperitivos/indice.html
{% extends 'base/base.html' %}
{% load static %}
{% block titulo %}Lista de Todos os Vídeos Gratuitos{% endblock titulo%}
{% block descricao %}Página com vídeo gratuito de Python{% endblock descricao %}

{% block body %}
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="mt-4 mb-4">
					<h1>Lista de Vídeos Aperitivos</h1>
					<ol>
						{% for video in videos %}
							<li><a href="{{ video.get_absolute_url }}">{{ video.titulo | default:"Falkland Título" }}</a></li>
						{% empty %}
							<h5>Não encontrado nenhum vídeo de aperitivo.</h5>
						{% endfor %}
					</ol>
				</div>
			</div>
		</div>
	</div>
{% endblock body %}

pypro/aperitivos/templates/aperitivos/video.html
{% extends 'base/base.html' %}
{% load static %}
{% block titulo %}Video Aperitivo: Motivação{% endblock titulo%}
{% block descricao %}Página com vídeo gratuito de Python{% endblock descricao %}

{% block body %}
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="mt-4 mb-4">
					<h1>{{ video.titulo | default:'Faltando Título' }}</h1>
				</div>
					<iframe src="https://player.vimeo.com/video/{{ video.vimeo_id }}?h=e0df472a0d&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479" width="1280" height="720" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen title="Company Story"></iframe>
			</div>
		</div>
	</div>
{% endblock body %}

pypro/base/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block titulo %}Python Pro{% endblock titulo %}</title>

    <meta name="description" content="{% block descricao %}Página do curso Python Pro{% endblock descricao %}">

    <meta name="author" content="Carlos Henrique Soares">
  	<link rel="icon" type="image.png" href="{% static 'base/img/favicon.png' %}">
    <link href="{% static 'base/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'base/css/style.css' %}" rel="stylesheet">

  	<script src="{% static 'base/js/jquery.min.js' %}"></script>
    <script src="{% static 'base/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'base/js/scripts.js' %}"></script>
  </head>
  <body>
  <div class="container mt-3">
      <nav class="navbar navbar-expand-lg bg-dark navbar-dark">
	  <div class="container">
		<a class="navbar-brand" href="{% url 'base:home' %}">Python Pro</a>
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		  <span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarSupportedContent">
		  <ul class="navbar-nav me-auto mb-2 mb-lg-0">
			 <li class="nav-item dropdown">
                 <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Módulos</a>
                <ul class="dropdown-menu">
                    {% for modulo in MODULOS %}
                        <li><a class="dropdown-item" href="{{ modulo.get_absolute_url }}">{{ modulo.titulo }}</a></li>
                    {% endfor %}
                </ul>
            </li>
            <a href="https://plataforma.dev.pro.br/certificates/Q50LmK" target="_blank"><span  class="badge bg-success p-3">Certificado</span></a>
          </ul>
            {% if user.is_authenticated %}
                <div class="btn-group">
                  <button type="button" class="btn btn-info dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                      Olá, {{ user.first_name }}!
                  </button>
                  <ul class="dropdown-menu">
                      <li><a class="dropdown-item bg-danger text-white" href="{% url 'logout' %}">Sair</a></li>
                  </ul>
                </div>
            {% else %}
            <a href="{% url 'login' %}" class="btn btn-light" >Entrar</a>
            {% endif %}
		</div>
	  </div>
	</nav>

	{% block body %}{% endblock body %}

  	{% include 'base/footer.html' with contato_email='ramalho@python.com.br' only %}

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js" integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js" integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ" crossorigin="anonymous"></script>
    </div>
  </body>
</html>

pypro/base/templates/base/footer.html
<footer class="main-footer mt-5 pt-4 text-light">
    <div class="container">
        <div class="row">
            <div class="col">
                <h3>Entre em contato</h3>
                <address>
                    +55 12 997-411-854
                    <br>
                    <a href="{{ contato_email }}" class="text-light">{{ contato_email }}</a>
                </address>
            </div>
        </div>
    </div>
    <div class="container rights pb-4">
        <div class="row">
            <div class="col">
                {% now 'Y' %} Python Pro. Todos os direitos reservados.
            </div>
        </div>
    </div>
</footer>

pypro/base/templates/base/home.html
{% extends 'base/base.html' %}
{% load static %}
{% block titulo%}Python Pro - Home{% endblock titulo %}
{% block body%}
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="jumbotron">
				<h2>Curso de Python com Luciano Ramalho</h2>
				<h4 class="mt-4">Entre na fila de espera</h4>

				<!-- Begin Mailchimp Signup Form -->
				<form action="https://dev.us8.list-manage.com/subscribe/post?u=1b87db3de3bf4cdc72240a6c6&amp;id=67bfee8f58&amp;f_id=00f102e0f0"
					  method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="mailchimp" target="_blank" novalidate>
					<div class="mailchimp mb-5">
						<input type="email" value="" name="EMAIL" class="form-control mr-3 required" id="mce-EMAIL" required placeholder="exemplo@email.com">
				<span id="mce-EMAIL-HELPERTEXT" class="helper_text"></span>
						<div class="">
							<input type="submit" value="Salvar" name="subscribe" id="mc-embedded-subscribe" class="btn btn-primary ml-5">
						</div>
						<div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_1b87db3de3bf4cdc72240a6c6_67bfee8f58" tabindex="-1" value=""></div>
					</div>
				</form>

<!--End mc_embed_signup-->
				<p>
					Confira em breve mais informações sobre o curso que será ministrado pelo autor do livro
				</p>
			</div>
			<div class="row">
				<div class="col-md-12">
					<div class="card">
						<h5 class="card-header">
							Mais detalhe sobre o instrutor
						</h5>
						<div class="card-body" >
								<img src="{% static 'base/img/luciano-ramalho.png' %}" class="img-thumbnail float-md-start mr-5" alt="Foto Luciano Ramalho"/>
								<p>
									Ramalho é programador Python desde 1998, Fellow da Python Software Foundation; é sócio e professor do Python.pro.br – uma empresa de treinamento – e cofundador do Garoa Hacker Clube, o primeiro hackerspace do Brasil; e autor do livro
									<a href="https://pythonfluente.com/" target="_blank">Python Fluente</a>
								</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock body%}

pypro/modulos/templates/modulos/aula_detalhe.html
{% extends 'base/base.html' %}
{% load static %}
{% block titulo %}Aula: {{ aula.titulo }}{% endblock titulo%}
{% block descricao %}Página com vídeo da aula {{ aula.titulo }}{% endblock descricao %}

{% block body %}
	<nav aria-label="breadcrumb">
	  <ol class="breadcrumb mt-2">
		<li class="breadcrumb-item"><a href="{% url 'base:home' %}">Home</a></li>
		<li class="breadcrumb-item"><a href="{{ aula.modulo.get_absolute_url }}">{{ aula.modulo.titulo }}</a></li>
		<li class="breadcrumb-item active" aria-current="page">{{ aula.titulo }}</li>
	  </ol>
	</nav>
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="mt-4 mb-4">
					<h1>{{ aula.titulo | default:'Faltando Título' }}</h1>
				</div>
					<iframe src="https://player.vimeo.com/video/{{ aula.vimeo_id }}?h=e0df472a0d&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479" width="1280" height="720" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen title="Company Story"></iframe>
			</div>
		</div>
	</div>
{% endblock body %}

pypro/modulos/templates/modulos/indice.html
{% extends 'base/base.html' %}
{% load static %}
{% block titulo %}Lista de Módulos e Aulas{% endblock titulo%}
{% block descricao %}Página com detalhes dos módulos e aulas{% endblock descricao %}

{% block body %}
	<div class="container">
		{% for modulo in modulos %}
		<div class="row">
			<div class="col-md-12">
				<div class="mt-4 mb-4">
					<h1>{{ modulo.titulo }}</h1>
					<dl>
						<dt>Público</dt>
						<dd>{{ modulo.publico }}</dd>
						<dt>Descrição</dt>
						<dd>{{ modulo.descricao }}</dd>
					</dl>
					<h2>Aulas</h2>
					<ol>
						{% for aula in modulo.aulas %}
							<li><a href="{{ aula.get_absolute_url }}">{{ aula.titulo }}</a></li>
						{% endfor %}
					</ol>
					<hr>
				</div>
			</div>
		</div>
		{% endfor %}
	</div>
{% endblock body %}

pypro/modulos/templates/modulos/modulo_detalhe.html
{% extends 'base/base.html' %}
{% load static %}
{% block titulo %}{{ modulo.titulo }}{% endblock titulo%}
{% block descricao %}Página com detalhes do módulo {{ modulo.titulo }}{% endblock descricao %}

{% block body %}
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="mt-4 mb-4">
					<h1>{{ modulo.titulo }}</h1>
					<dl>
						<dt>Público</dt>
						<dd>{{ modulo.publico }}</dd>
						<dt>Descrição</dt>
						<dd>{{ modulo.descricao }}</dd>
					</dl>
					<h2>Aulas</h2>
					<ol>
						{% for aula in aulas %}
							<li><a href="{{ aula.get_absolute_url }}">{{ aula.titulo }}</a></li>
						{% endfor %}
					</ol>
				</div>
			</div>
		</div>
	</div>
{% endblock body %}

pypro/turmas/templates/turmas/indice.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Turmas</h1>
</body>
</html>